### ISSUE TITLE
Исправление PHP Notice: Undefined index

### ISSUE THREAD

**Issue by paulmann** [vldud/tega.ordersimple#2]
Для исправления ошибки нужно сменить все

`\$(\w+)\["(\w+)"] \!= ""` и `\(\$(\w+)\["(\w+)"] != 0\)`

на

`!empty($$1["$2"])`

**Comment by vldud** [comment]
Частично исправлено. Основная масса ошибок порождается ядром Битрикс, а не кодом компонента.
